# Generated by Django 5.0.3 on 2024-05-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='uploads/blog/')),
                ('description', models.TextField()),
                ('title2', models.CharField(blank=True, max_length=250)),
                ('description2', models.TextField(blank=True, default='', null=True)),
                ('title3', models.CharField(blank=True, max_length=250)),
                ('description3', models.TextField(blank=True, default='', null=True)),
                ('point1', models.CharField(blank=True, max_length=250, null=True)),
                ('des1', models.TextField(blank=True, default='', null=True)),
                ('point2', models.CharField(blank=True, max_length=250, null=True)),
                ('des2', models.TextField(blank=True, default='', null=True)),
                ('point3', models.CharField(blank=True, max_length=250, null=True)),
                ('des3', models.TextField(blank=True, default='', null=True)),
                ('point4', models.CharField(blank=True, max_length=250, null=True)),
                ('des4', models.TextField(blank=True, default='', null=True)),
                ('point5', models.CharField(blank=True, max_length=250, null=True)),
                ('des5', models.TextField(blank=True, default='', null=True)),
                ('point6', models.CharField(blank=True, max_length=250, null=True)),
                ('des6', models.TextField(blank=True, default='', null=True)),
                ('point7', models.CharField(blank=True, max_length=250, null=True)),
                ('des7', models.TextField(blank=True, default='', null=True)),
                ('point8', models.CharField(blank=True, max_length=250, null=True)),
                ('des8', models.TextField(blank=True, default='', null=True)),
                ('point9', models.CharField(blank=True, max_length=250, null=True)),
                ('des9', models.TextField(blank=True, default='', null=True)),
                ('point10', models.CharField(blank=True, max_length=250, null=True)),
                ('des10', models.TextField(blank=True, default='', null=True)),
                ('bolg_date', models.DateField()),
                ('blog_time', models.TimeField()),
                ('blog_writer', models.CharField(max_length=250)),
            ],
        ),
    ]
